resources:
- name: go-modules-test
  type: git
  source:
    uri: https://github.com/qcu87z/go-module-test.git
    branch: master

jobs:
- name: lint-the-world
  public: true
  plan:
  - get: go-modules-test
  - task: lint
    file: concourse-tasks/lint.yml